name: cword
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.1

  # tools
  logman: ^0.0.21
  shared_preferences_explorer: ^0.1.0

  # bloc packages
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5

  dio: ^5.7.0
  go_router: ^14.6.2
  flutter_screenutil: ^5.9.3
  encrypt: ^5.0.3
  toastification: ^2.3.0
  widget_marquee: ^0.0.8
  swipeable_page_route: ^0.4.6
  animated_theme_switcher: ^2.0.10
  data_table_2: ^2.5.18

  # plugins
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  sqflite_common_ffi: ^2.3.4+4
  window_manager: ^0.4.3

  ionicons: ^0.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/i18n/
    - resources/flags/
    - resources/images/
    - resources/images/svg/
    - resources/images/png/
    - resources/images/app/
    - resources/animations/
    - resources/animations/lottie/

  fonts:
    - family: WixMadeforDisplay
      fonts:
        - asset: resources/fonts/WixMadeforDisplay-VariableFont_wght.ttf
